version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    target-branch: "main"  # Specify the branch you want to update
    reviewers:
      - "distortion2112"  # Add GitHub usernames of reviewers
    assignees:
      - "distortion2112"  # Add GitHub usernames of assignees
    automerge: true  # Enable auto-merge if all checks pass
    ignore:
      - dependency-name: "example-package"
        versions: ["0.0.1"]